# Generated by Django 2.2.3 on 2020-02-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToTheBeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('college', models.TextField(max_length=500)),
                ('email', models.TextField()),
                ('contactno', models.TextField(max_length=11)),
            ],
        ),
    ]
