# Generated by Django 2.2.3 on 2020-02-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tothebeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agt',
            name='college',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='agt',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
