# Generated by Django 2.2.3 on 2020-02-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200202_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tothebeatgroup',
            name='college',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tothebeatgroup',
            name='leader_contactno',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tothebeatgroup',
            name='leader_name',
            field=models.TextField(),
        ),
    ]
