# Generated by Django 3.0.3 on 2020-02-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('college', models.TextField()),
                ('email', models.TextField()),
                ('contactno', models.TextField()),
                ('perform', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Antra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('college', models.TextField(max_length=500)),
                ('email', models.TextField()),
                ('contactno', models.TextField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='BigRoar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('college', models.TextField(max_length=500)),
                ('email', models.TextField()),
                ('contactno', models.TextField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Craftix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('college', models.TextField(max_length=500)),
                ('email', models.TextField()),
                ('contactno', models.TextField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='kavyanjali',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('college', models.TextField(max_length=500)),
                ('email', models.TextField()),
                ('contactno', models.TextField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='TalkMasters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('college', models.TextField(max_length=500)),
                ('email', models.TextField()),
                ('contactno', models.TextField(max_length=11)),
                ('topic', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='ToTheBeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('college', models.TextField(max_length=500)),
                ('email', models.TextField()),
                ('contactno', models.TextField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='ToTheBeatGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.TextField()),
                ('college', models.TextField()),
                ('email', models.TextField()),
                ('leader_contactno', models.TextField()),
                ('number_of_part', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vyaktitva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('college', models.TextField(max_length=500)),
                ('email', models.TextField()),
                ('contactno', models.TextField(max_length=11)),
            ],
        ),
    ]
